### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by DumboOctopus** [DumboOctopus/random-walk-images#3]
Move all the options into a configuration.yaml file.
Usage
   `python rwalk.py config.yaml`
if arguments are passed, they will override the options given in the config (but they will not change the file itself). The -c tag should become deprecated.

Highest priority to settings:
1. Config File
2. Command line args
3. Defaults in system.

Example YAML file:
```
background: [hex or tuple or sub list with r g and b values]
width: <int>
height: <int>
iterations: <int>
thread: <boolean>
noshow: <boolean>
file: [Filename which can include the special word $t which will be replaced with a timestamp]
walkers: 
  - walker_name:
      color: [hex or tuple or sub list with r g and b values]
      position: [random or xy tuple]
      iterations: <int> (overrides iterations for this specific walker)
      margin-[left|right|top|bottom\""]: <int>

```
