### ISSUE TITLE
Do not move over edge

### ISSUE THREAD

**Issue by DumboOctopus** [DumboOctopus/random-walk-images#6]
When it reaches a boundary, it does not loop to the other side.
```
walkers:
  - walker:
     ...
     edges: wrap | hard # default wrap should not be a required field.
```
